version: '3'
services:

  # PHP
  runtimy_php_service:
    image: runtimy_php_image
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: runtimy_php_container
    restart: unless-stopped
    tty: true
    environment:
      CONTAINER_ROLE: app
      SERVICE_NAME: runtimy_php_service
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - runtimy-network

  # Scheduler
  runtimy_scheduler_service:
    image: runtimy_php_image
    container_name: runtimy_scheduler_container
    depends_on:
      - runtimy_php_service
    restart: unless-stopped
    tty: true
    environment:
      CONTAINER_ROLE: scheduler
      SERVICE_NAME: runtimy_scheduler_service
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - runtimy-network

  # SSH for Invoker access
  runtimy_ssh_service:
    image: runtimy_ssh_image
    container_name: runtimy_ssh_container
    build:
        context: .
        dockerfile: ./docker/ssh/Dockerfile
    restart: on-failure
    ports:
        - '2277:22'
    links:
        - runtimy_mysql_service
        - runtimy_php_service
    volumes:
        - ./:/var/www
    networks:
        - runtimy-network

  # Nginx
  runtimy_nginx_service:
    image: nginx:alpine
    container_name: runtimy_nginx_container
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_LOCAL_PORT}:80"
      # - "443:443" SSL Пока что нет
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - runtimy-network

  # MySQL
  runtimy_mysql_service:
    image: mysql:5.7.22
    container_name: runtimy_mysql_container
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: runtimy_mysql_service
    volumes:
      - runtimy_mysql_data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - runtimy-network

networks:
  runtimy-network:
    driver: bridge
volumes:
  runtimy_mysql_data:
    driver: local
